language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t accarter/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true accarter/docker-react npm run test